#!/usr/bin/env bash
# Idempotent local-env bootstrap for Cloud Agent environments.
#
# The app hard-requires a syntactically valid Supabase URL (createClient throws at
# import time otherwise) and a valid API base URL (Next's fetch cache hangs on a
# malformed `undefined/...` URL). This writes non-secret placeholder defaults so the
# app boots and every page renders locally without the owner's private credentials.
#
# Real values (Supabase project, external API, integrations) belong in Cursor Secrets:
# those are injected as process env vars and take precedence over this file, because
# Next.js never overrides an already-set process.env variable with a .env entry.
#
# Only creates .env when absent, so a real developer .env is never clobbered.
set -euo pipefail

cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo "[setup-env] .env already present — leaving it untouched."
  exit 0
fi

cat > .env <<'ENV'
# Local development defaults generated by .cursor/setup-env.sh.
# Supply real values via Cursor Secrets (they override these at runtime).

DOMAIN=https://nateee.com

# Supabase — placeholder URL/key so createClient() does not throw at import time.
# Unused local port => data queries fail fast (ECONNREFUSED) instead of hanging.
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=placeholder-anon-key

# External backend API. Unused local port => server/client fetches fail fast and fall
# back to empty state, instead of hanging on Next's fetch cache when the value is unset.
API_URL=http://127.0.0.1:9
NEXT_PUBLIC_API_URL=http://127.0.0.1:9
ENV

echo "[setup-env] wrote placeholder .env"
